<div class="menueDiv" id="menueId">
<ul>
    <li>Frontend
        <ul>
            <li>Design
                <ul>
                    <li>Design-tools</li>
                    <li>Design-Rules</li>
                    <li>Graphic Resources</li>
                    <li>Inspiration</li>
                </ul>
            </li>
            <li>Sprachen
                <ul>
                    <li>HTML5</li>
                    <li>CSS3</li>
                    <li>JavaScript</li>
                    <li>TypeScript</li>
                </ul>
            </li>
            <li>Frameworks
                <ul>
                    <li>Bootstrap</li>
                    <li>Angular</li>
                    <li>Ionic</li>
                    <li>Vue</li>
                    <li>React</li>
                </ul>
            </li>
        </ul>
    </li>
    <li>Backend
    <ul>
            <li>Datenbanken
                <ul>
                    <li>Clients</li>
                    <li>MySql</li>
                </ul>
            </li>
            <li>Sprachen
                <ul>
                    <li>PHP</li>
                    <li>Java</li>
                </ul>
            </li>
            <li>Frameworks
                <ul>
                    <li>Laravel</li>
                    <li>Python</li>
                    <li>Ruby On Rails</li>
                    <li>Node.js</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
</div>
